services:
  qnx-monitor:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    container_name: qnx-monitor
    command: --ip-file /app/config/ips.txt
    volumes:
      - ./config:/app/config:ro
    tty: true
    network_mode: "host"
    stdin_open: true
    restart: unless-stopped
